services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=libmanage'
      - 'POSTGRES_PASSWORD=1Q2W3E4R5'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432:5432'
