services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=libmanage'
      - 'POSTGRES_PASSWORD=1Q2W3E4R5'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5433:5433'

  libmanage-app:
    build: .
    ports:
      - '8080:8080'
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/libmanage
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1Q2W3E4R5
